deepjavalibrary/djl-demo

live-object-detection/build.gradle, live-object-detection/src/main/java/com/examples/WebCam.java
The sarxos-webcam library is a really convenient way to get webcam support for Java applications that doesn't require OpenCV. I think this would make it easier for other users to try out this code.
=> Using new library for webcam capture so OpenCV is not required

graalvm/pom.xml
Add `--report-unsupported-elements-at-runtime` to avoid compilation failure
=> Add config to enable PyTorch graalvm

android/pytorch_android/gradle, android/pytorch_android/gradlew
This broken link basically killed the docs build since it is not found
=> fix on broken sym link

.github/workflows/canary-centos.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, aws/beanstalk-model-serving/build.gradle, canary/build.gradle, developement/fatjar/build.gradle, developement/fatjar/pom.xml, developement/module/build.gradle, developement/multi-engine/build.gradle, huggingface/hybrid/build.gradle, web-demo/interactive-console/build.gradle, web-demo/interactive-console/src/main/resources/starter/mxnet.gradle, web-demo/interactive-console/src/main/resources/starter/pytorch.gradle, web-demo/interactive-console/src/main/resources/starter/tensorflow.gradle
This also adds an option to run canaries with a specific pytorch version.
=> Update canary and demos for 0.17.0 release

.github/workflows/canary-gpu-cuda-102.yml, .github/workflows/canary-gpu-cuda-112.yml, .github/workflows/canary-gpu-cuda-113.yml
Add gpu canary actions in parity with what we have in codebuild. 
Cuda 10.2 and Cuda 11.3 canaries are working fully in parity with what we have in codebuild.
- cuda 10.2 https://github.com/deepjavalibrary/djl-demo/actions/runs/2841970595
- cuda 11.3 https://github.com/deepjavalibrary/djl-demo/actions/runs/2842398240
Cuda 11.2 works except when testing `DJL_ENGINE=mxnet-native-cu112mkl`. The issue seems to be that we're not downloading/extracting the other .so files necessary from s3. This doesn't seem like an issue with the canary action, but I need to continue investigating that. The equivalent canary in codebuild hasn't been successful in a long time, so this might point to a real failure.
Failure for cuda 11.2 https://github.com/deepjavalibrary/djl-demo/runs/7794346123?check_suite_focu …
=> Add gpu canary builds

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-gpu-cuda-102.yml, .github/workflows/canary-gpu-cuda-112.yml, .github/workflows/canary-gpu-cuda-113.yml
Fixes the mxnet cu112 canary - uses version 1.9.1 which has the full jar file. https://github.com/deepjavalibrary/djl-demo/actions/runs/2848741447
I also tested with an update to the 1.9.0 binaries in staging repo aidjl-1195 and it works, so we can also publish an updated set of 1.9.0 binaries and test that here as well if we want (only cu112 is broken for mxnet right now). Here's the run using the staging repo contained the fixed 1.9.0 cu112 binaries https://github.com/deepjavalibrary/djl-demo/actions/runs/2849154026. 
Basic question: Does promoting the staging repo with fixed 1.9.0 binaries overwrite the current binaries in the release repo?
=> update self-hosted canary tests

.github/workflows/canary-gpu.yml
Cuda102 for pytorch is currently using 1.13.0, but we have moved to 1.13.1.
Pytorch 1.13.x doesn't support Cuda102 anymore so the test just fetches cpu version. We're not updating 1.13.0 anymore.
=> Update pytorch canary for cuda102 to 1.13.1

aws/sagemaker/large-model-inference/README.md, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_deploy_llama2-13b-gptq.ipynb
=> add gptq notebook sample

CODE_OF_CONDUCT.md, android/pytorch_android/quickdraw_recognition/README.md, aws/inferentia/README.md, aws/inferentia/inf1.md, development/multi-engine/performance_numbers.md, djl-serving/python-mode/stable-diffusion/docs/README.md, huggingface/inferentia/README.md, malicious-url-detector/docs/translators.md
Headers should be an h1 to resolve to a header on the docs build.
=> Fix markdown headers

aws/sagemaker/large-model-inference/README.md, aws/sagemaker/large-model-inference/sample-llm/ds_deploy_llama2-13b-smoothquant.ipynb
Add a smoothquant notebook demo for newest container - This will require follow up after the SDK deploys to make sure that it works on SageMaker as is, or if we need to clean up the properties.
=> [feat] Add deepspeed smoothquant notebook

aws/sagemaker/notebook/README.md, jupyter/BERTQA.ipynb, jupyter/Dockerfile, jupyter/README.md, jupyter/docker-compose.yml, jupyter/load_mxnet_model.ipynb, jupyter/load_pytorch_model.ipynb, jupyter/mxnet/load_your_own_mxnet_bert.ipynb, jupyter/object_detection_with_model_zoo.ipynb, jupyter/onnxruntime/machine_learning_with_ONNXRuntime.ipynb, jupyter/paddlepaddle/face_mask_detection_paddlepaddle.ipynb, jupyter/paddlepaddle/face_mask_detection_paddlepaddle_zh.ipynb, jupyter/paddlepaddle/paddle_ocr_java.ipynb, jupyter/paddlepaddle/paddle_ocr_java_zh.ipynb, jupyter/pytorch/load_your_own_pytorch_bert.ipynb, jupyter/rank_classification_using_BERT_on_Amazon_Review.ipynb, jupyter/tensorflow/pneumonia_detection.ipynb, jupyter/tensorflow/rank_classification_using_BERT_on_Amazon_Review.ipynb, jupyter/tensorflow_lite/inference_with_tensorflow_lite.ipynb, jupyter/test_notebook.sh, jupyter/transfer_learning_on_cifar10.ipynb, jupyter/tutorial/01_create_your_first_network.ipynb, jupyter/tutorial/02_train_your_first_model.ipynb, jupyter/tutorial/03_image_classification_with_your_model.ipynb, jupyter/tutorial/README.md
This moves the jupyter notebooks from the main repo to demos. It follows the trend where the main tracks master while demo tracks releases or nightly snapshots.
Combined with https://github.com/deepjavalibrary/djl/pull/2854
=> Moves the jupyter notebooks from main repo

.github/workflows/canary-aarch64-linux.yml
add xgboost to aarch64 canary test since we support it now
=> [canary] add xgboost to aarch64 canary tests

.github/workflows/canary-m1-mac.yml
This switches the M1 canary to use the new GitHub actions hosted M1 runner.
Successful run: https://github.com/deepjavalibrary/djl-demo/actions/runs/7561989033/job/20591460285
=> Use GitHub Actions M1 runner

.github/workflows/canary-m1-mac.yml
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
Run: https://github.com/deepjavalibrary/djl-demo/actions/runs/7715985234
=> Switch to cheaper M1

.github/workflows/nightly.yml
Removing quarkus from nightly as it is no longer being actively maintained and now fails CI. Previous version of DJL will be available to support quarkus.
=> [ci] remove Quarkus test from nightly

.github/workflows/nightly.yml
Removing the graalvm nightly test from CI.
=> [ci] Remove graavlm from nightly tests

apache-spark/notebook/Image_Classification_Spark.ipynb
Changes 
- Removed comma that was corrupting notebook 
Methodology and Testing
- Attempted to open the notebook in VS Code, which resulted in a "not valid JSON" error.
- Opened the notebook in a text editor and identified the issue.
- Removed the offending comma.
- Re-opened the notebook in VS Code successfully without errors.
=> [jupyter] Removed Comma Corrupting Image Classification Notebook

.github/workflows/canary-aarch64-linux.yml
fixes canary for aarch64-linux sentencepiece by installing required libatomic. WF run https://github.com/deepjavalibrary/djl-demo/actions/runs/11872855959
=> [canary][aarch64] install libatomic1 for sentencepiece

gradle.properties
DJL Demo nightly canary has been failing because 0.31.0-snapshot expired.
=> update djl version to 0.32.0-snapshot

jupyter/README.md
=> [doc] Fix broken link in jupyter readme

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-al2.yml, .github/workflows/canary-gpu.yml, .github/workflows/canary-m1-mac.yml, .github/workflows/canary-ubuntu.yml
The below are the pytorch engine versions we officially publish to support various cuda versions. 
- PT 1.13.1 is for PT 1.x support, and CUDA 11.x support
- PT 2.1.2 is for Neuron support (latest supported version on neuron)
- PT 2.3.1 is for CUDA 12.1 support
- PT 2.5.1 is for CUDA 12.4 support
So, removing 2.4.0 from canaries as dont publish it anymore.
=> [canary-gpu] remove pytorch 2.4.0 test from canary

quarkus/example/pom.xml
issue number:
#539 
use pytorch-jni, pytorch-native-cpu dependency directly 
tested on Windows and MacOs M1
( By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice. )
=> fix the pytorch-native-auto dependency issue in quarkus example

djl-serving/postman-client/DJLServing.postman_collection.json, djl-serving/python-client/djlserving_client_example3.py
***Context:***
djl-serving 0.31.0 ( installed by brew )
python-client and postman-client 
example3_predict
***Error Message:***
{
"code": 400,
"type": "TranslateException",
"message": "Missing \"inputs\" in json."
}
Use expected field "inputs" instead of "data"
=> fix the failed DJLServing Example3: JSON POST Request Uses Incorrect field

graalvm/pom.xml
#545
DJL Version: 0.30.0
JavaCPP Version: 1.5.7
DJL throws a `NoSuchMethodError` when attempting to load the TensorFlow engine because the required method `Loader.loadProperties(boolean)` is not present in JavaCPP version 1.5.7.
The TensorFlow engine should initialize successfully without any errors, allowing DJL to perform TensorFlow-based operations.
JavaCPP 1.5.11 works 
=> upgrade javacpp version to 1.5.11 to fix the TF engine init failure in Graalvm example

.github/workflows/canary-ubuntu.yml
=> [canary] remove ubuntu20.04 canary due to gh action runner deprecation
