deepjavalibrary/djl-demo

spark/image-classification/src/main/scala/com/examples/Example.scala
remove redundant post processing section
=> [Spark] remove redundant postprocessing

covid19-detection/build.gradle, covid19-detection/src/main/java/com/examples/Covid19Detection.java
=> Fix Covid19Detection criteria

README.md, visualization/README.md
=> Update training visualizaition README

README.md, lambda-model-serving/README.md, lambda-model-serving/build.gradle
=> Update serverless model serving document

aws-kinesis-video-streams/build.gradle, covid19-detection/build.gradle, lambda-model-serving/README.md, lambda-model-serving/build.gradle, live-object-detection/build.gradle, malicious-url-detector/build.gradle, spark/image-classification/build.gradle
=> Upgrade to DJL 0.5.0 version

spark/image-classification/README.md, spark/image-classification/build.sbt
=> Update DJL 0.5.0 version for spark README

spark/image-classification/README.md, spark/image-classification/src/main/scala/com/examples/DataProcessExample.scala, spark/image-classification/src/main/scala/com/examples/ImageClassificationExample.scala
Users find the existing spark example hard to understand, add a scratch template for them to play with.
=> add a scratch template for Spark example

web-demo/doodle_game/frontend/app.js, web-demo/doodle_game/frontend/index.html
better touch screen support on phone
=> add touchscreen support

web-demo/doodle_game/frontend/app.css
=> add support on iphone

android/quickdraw_recognition/build.gradle
Bump up the android package version
=> Bump up the android package version

web-demo/interactive-console/src/main/webapps/app.js
=> Add https portal for interactive console

web-demo/interactive-console/src/main/java/ai/djl/examples/jshell/InteractiveShell.java, web-demo/interactive-console/src/main/java/ai/djl/examples/jshell/ShellController.java
Fix no memory issue on interactive console
=> add timer and timedtask for inferactive console

web-demo/interactive-console/src/main/webapps/app.js
fix copy problem on xterm. Current copy paste will show double paste message
=> fix copy problem

README.md, lambda-model-serving/README.md
=> Updated README files

web-demo/interactive-console/build.gradle, web-demo/interactive-console/src/main/java/ai/djl/examples/jshell/ShellSpawner.java
upgrade the version to snapshot version for more functionalities
=> upgrade version to snapshot

web-demo/interactive-console/src/main/java/ai/djl/examples/jshell/BlockRunnerController.java, web-demo/interactive-console/src/main/resources/starter/gradle/wrapper/GradleWrapperDownloader.java, web-demo/interactive-console/src/main/resources/starter/gradle/wrapper/gradle-wrapper.properties, web-demo/interactive-console/src/main/resources/starter/gradlew, web-demo/interactive-console/src/main/resources/starter/gradlew.bat, web-demo/interactive-console/src/main/resources/starter/mxnet.gradle, web-demo/interactive-console/src/main/resources/starter/pytorch.gradle, web-demo/interactive-console/src/main/resources/starter/tensorflow.gradle, web-demo/interactive-console/src/main/webapps/blockrunner/app.js, web-demo/interactive-console/src/main/webapps/blockrunner/index.html
Create a template generator from block runner
=> add template generator

web-demo/interactive-console/src/main/webapps/blockrunner/app.js, web-demo/interactive-console/src/main/webapps/jshell/app.js
change ports to djl based location
=> change ports

web-demo/interactive-console/src/main/java/ai/djl/examples/jshell/ShellSpawner.java
Add apache commons missing dependency
=> add apache commons dependecy

live-object-detection/README.md
=> Add setup instruction for live-object-detection

spark/image-classification/README.md, spark/image-classification/src/main/scala/com/examples/ImageClassificationExample.scala
Add TensorFlow package in the Spark tutorial
=> add Spark support on TensorFlow

beanstalk-model-serving/.gitignore, beanstalk-model-serving/README.md, beanstalk-model-serving/build.gradle, beanstalk-model-serving/cleanup.sh, beanstalk-model-serving/deploy.sh, beanstalk-model-serving/elasticbeanstalk-role.json, beanstalk-model-serving/options.json, beanstalk-model-serving/src/main/java/com/example/doodle/DoodleController.java, beanstalk-model-serving/src/main/resources/application.yml
=> Add command line to deploy to beanstalk

pneumonia-detection/README.md, pneumonia-detection/src/main/java/com/examples/PneumoniaDetection.java
=> Update test image and model url

android/README.md, android/build.gradle, android/quickdraw_recognition/src/main/java/ai/djl/examples/quickdraw/DoodleModel.java
Apply some fix on Android example.
=> fix android example

android/build.gradle, android/quickdraw_recognition/build.gradle
=> bump us version

aws/aws-kinesis-video-streams/build.gradle, aws/aws-kinesis-video-streams/src/main/java/com/examples/DjlImageVisitor.java
=> Upgrade kinesis project to DJL 0.6.0

live-object-detection/build.gradle, live-object-detection/src/main/java/com/examples/WebCam.java
=> Upgrade live object detection project to DJL 0.6.0

malicious-url-detector/build.gradle, malicious-url-detector/src/main/java/com/example/MaliciousURLModel.java, malicious-url-detector/src/main/java/com/example/ModelTrainer.java, malicious-url-detector/src/main/java/com/example/URLTranslator.java
=> Upgrade malicious url detector project to DJL 0.6.0

aws/beanstalk-model-serving/README.md, aws/beanstalk-model-serving/build.gradle, aws/lambda-model-serving/build.gradle, aws/lambda-model-serving/src/main/java/com/examples/Handler.java, multi-engine/build.gradle
=> Update lambda beanstalk and multi-engine to DJL 0.6.0

web-demo/interactive-console/build.gradle, web-demo/interactive-console/src/main/java/ai/djl/examples/jshell/ShellSpawner.java
Fix some bugs on versioning for interactive shell
=> interactive shell updates

web-demo/interactive-console/src/main/java/ai/djl/examples/jshell/ShellController.java
=> Add static landing page to demo web site

web-demo/doodle_game/backend/build.gradle, web-demo/doodle_game/backend/src/main/java/ai/djl/examples/doodle/Handler.java
=> Upgrade doodle_grame to DJL 0.6.0

web-demo/doodle_game/frontend/app.js
=> update invoke url

spark/image-classification/README.md, spark/image-classification/build.gradle, spark/image-classification/build.sbt, spark/image-classification/src/main/scala/com/examples/DataProcessExample.scala, spark/image-classification/src/main/scala/com/examples/ImageClassificationExample.scala
=> update spark example

android/quickdraw_recognition/src/main/java/ai/djl/examples/quickdraw/PaintView.java, android/quickdraw_recognition/src/main/res/layout/activity_doodle.xml
=> Fix layout issue and out of bound bug

android/README.md, aws/beanstalk-model-serving/src/main/java/com/example/doodle/DoodleController.java, spark/image-classification/src/main/scala/com/examples/DataProcessExample.scala, web-demo/doodle_game/backend/src/main/java/ai/djl/examples/doodle/Handler.java
=> Update DoodleDraw README and download url

android/quickdraw_recognition/src/main/java/ai/djl/examples/quickdraw/PaintView.java
reduce computation power for the inference
=> reduce some computation power on cropping

android/quickdraw_recognition/src/main/AndroidManifest.xml, android/quickdraw_recognition/src/main/java/ai/djl/examples/quickdraw/DoodleDrawActivity.java, android/quickdraw_recognition/src/main/java/ai/djl/examples/quickdraw/PaintView.java, android/quickdraw_recognition/src/main/res/layout/activity_doodle.xml, android/quickdraw_recognition/src/main/res/values/dimes.xml, android/quickdraw_recognition/src/main/res/values/strings.xml, android/quickdraw_recognition/src/main/res/xml/filepaths.xml
=> Add share feature to doodle draw

android/quickdraw_recognition/build.gradle, android/quickdraw_recognition/src/main/java/ai/djl/examples/quickdraw/DoodleModel.java, android/quickdraw_recognition/src/main/java/ai/djl/examples/quickdraw/PaintView.java
=> simplify the android example

footwear_classification/.gitignore, footwear_classification/build.gradle, footwear_classification/src/main/java/com/examples/Inference.java, footwear_classification/src/main/java/com/examples/Training.java
=> Upgrade to DJL 0.7.0-SNAPSHOT version

footwear_classification/.gitignore, footwear_classification/README.md, footwear_classification/src/main/java/com/examples/Inference.java
=> Add README.md for footwear classification

android/.gitignore, android/build.gradle, android/quickdraw_recognition/build.gradle
=> Update android sdk version

graalvm/pom.xml, gradle/wrapper/gradle-wrapper.properties
=> Use 0.7.0-SNAPSHOT for graalvm project

.github/workflows/nightly.yml, docs/README.md, docs/mkdocs.yml
@stu1130 @zachgk @lanking520 @roywei @frankfliu 
Added mkdocs build folder to create documentation. Added nightly build YML file to build website folder.
- Would need additions to the nightly.yml file such as add aws credentials part along with creation of S3 bucket to host the website using Route53.
=> Documentation using mkdocs and adding nightly build file to build site.

quarkus/src/main/resources/application.properties
=> Fix tensorflow quarkus crash

.github/workflows/nightly.yml
Use S3 to upload the document website
=> Add workflow to allow S3 uploading

.github/workflows/nightly.yml, visualization/README.md
add some documentation fix for the website generation and change CI correspondingly
=> update documentation and change CI to weekly

README.md, apache-beam/ctr-prediction/README.md, docs/mkdocs.yml, flink/sentiment-analysis/README.md
Add beam and flink examples to main README. Minor improvements to their individual READMEs.
=> Add beam/flink to README

android/quickdraw_recognition/build.gradle
=> Upgrade to DJL 0.7.0 for android demo

aws/aws-kinesis-video-streams/build.gradle, aws/aws-kinesis-video-streams/src/main/java/com/examples/App.java, aws/aws-kinesis-video-streams/src/main/java/com/examples/AppOnFile.java, aws/aws-kinesis-video-streams/src/main/java/com/examples/DjlImageVisitor.java, aws/beanstalk-model-serving/build.gradle, aws/emr-distributed-inference/build.gradle, aws/lambda-model-serving/build.gradle, footwear_classification/build.gradle, footwear_classification/src/main/java/com/examples/Training.java, graalvm/pom.xml, malicious-url-detector/README.md, malicious-url-detector/build.gradle, malicious-url-detector/src/main/java/com/example/CSVDataset.java, malicious-url-detector/src/main/java/com/example/MaliciousURLModel.java, malicious-url-detector/src/main/java/com/example/ModelTrainer.java, multi-engine/build.gradle, pneumonia-detection/build.gradle, quarkus/pom.xml, spark/image-classification/build.gradle, spark/image-classification/build.sbt, web-demo/doodle_game/backend/build.gradle, web-demo/interactive-console/build.gradle, web-demo/interactive-console/src/main/java/ai/djl/examples/jshell/ShellSpawner.java, web-demo/interactive-console/src/main/resources/starter/mxnet.gradle, web-demo/interactive-console/src/main/resources/starter/pytorch.gradle, web-demo/interactive-console/src/main/resources/starter/tensorflow.gradle
=> Upgrade to DJL 0.7.0 release

.github/workflows/canary-centos.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-windows.yml
Add Mac, CentOS:7 and Windows 2016 2019 platform
=> Add multiple canaries platforms

.github/workflows/demo-doc.yml, docs/README.md
Current Document invalidation is failing, added a documentation build
=> add update on documentation build

.github/workflows/canary-centos.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, .github/workflows/demo-doc.yml
1. Added tensorflow cpu test
2. Fixed windows job only run first command issue
=> Add tensorflow cpu canary test

aws/aws-kinesis-video-streams/build.gradle, aws/beanstalk-model-serving/build.gradle, aws/emr-distributed-inference/build.gradle, aws/lambda-model-serving/build.gradle, flink/sentiment-analysis/build.gradle, footwear_classification/build.gradle, live-object-detection/build.gradle, malicious-url-detector/build.gradle, multi-engine/build.gradle, pneumonia-detection/build.gradle, web-demo/doodle_game/backend/build.gradle, web-demo/interactive-console/build.gradle
=> Fix minor build.gradle script bug

canary/build.gradle, canary/gradle.properties
=> Update canary test to 0.8.0

apache-beam/ctr-prediction/README.md, apache-beam/ctr-prediction/pom.xml, apache-beam/ctr-prediction/src/main/java/org/example/ctrprediction/CtrPrediction.java, aws/aws-kinesis-video-streams/build.gradle, aws/beanstalk-model-serving/build.gradle, aws/emr-distributed-inference/build.gradle, aws/lambda-model-serving/build.gradle, flink/sentiment-analysis/build.gradle, flink/sentiment-analysis/src/main/java/com/example/SentimentAnalysis.java, footwear_classification/build.gradle, graalvm/pom.xml, malicious-url-detector/build.gradle, multi-engine/build.gradle, pneumonia-detection/build.gradle, quarkus/pom.xml, spark/image-classification/build.gradle, spark/image-classification/build.sbt, web-demo/doodle_game/backend/build.gradle, web-demo/interactive-console/build.gradle
=> Update demo projects to DJL 0.8.0

graalvm/README.md, graalvm/pom.xml, graalvm/src/main/java/com/example/ImageClassification.java, quarkus/src/main/java/com/example/ImageClassification.java
=> Workaround tensorflow model zoo bug

aws/emr-distributed-inference/dataprocess/README.md, aws/emr-distributed-inference/dataprocess/build.gradle, aws/emr-distributed-inference/image-classification-gpu/README.md, aws/emr-distributed-inference/image-classification-gpu/build.gradle, aws/emr-distributed-inference/image-classification-gpu/emr-prepare.sh, aws/emr-distributed-inference/image-classification-gpu/src/main/scala/com/examples/ImageClassificationExample.scala
Add yarn cluster configuration for EMR on GPU
=> add emr yarn cluster for spark gpu

.github/workflows/demo-doc.yml, aws/emr-distributed-inference/dataprocess/README.md, docs/mkdocs.yml
Fix broken links in the demo docs
=> fix broken links

.github/workflows/canary-centos.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml
setEnv is disabled in GitHub Action. Now we just need to manually set it in the front
=> add env settting to the front

aws/emr-distributed-inference/image-classification-gpu/README.md, aws/emr-distributed-inference/image-classification-gpu/build.gradle, aws/emr-distributed-inference/image-classification-gpu/configurations.json, aws/emr-distributed-inference/image-classification-gpu/install_spark.sh
Upgrade Spark 3.0 GPU example with EMR 6.2.0
=> Add EMR 6.2.0 support

.github/workflows/canary-centos.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, canary/build.gradle, canary/gradle.properties, canary/src/main/java/ai/djl/canary/CanaryTest.java
=> Update to DJL 0.9.0

.github/workflows/canary-centos.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, canary/build.gradle, canary/src/main/java/ai/djl/canary/CanaryTest.java
=> Add onnxruntime and DLR canary test

aws/emr-distributed-inference/image-classification-gpu/README.md
Fixed EMR configuration json url
=> fix emr url

visualization/djl-ui/frontend/package.json
=> Update the dependencies to avoid security issues

android/quickdraw_recognition/build.gradle
=> Bump up DJL version

.github/workflows/canary-centos.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, canary/build.gradle, canary/src/main/java/ai/djl/canary/CanaryTest.java
=> add TFLite canary

.github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, canary/build.gradle
=> add tflite cpu canary

.github/workflows/canary-centos.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, canary/build.gradle, canary/src/main/java/ai/djl/canary/CanaryTest.java
Add paddlepaddle to canary test
=> add paddlepaddle to canary

.github/workflows/canary-centos.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, canary/build.gradle
add option to specify djl version
=> add djl version in canary

aws/sagemaker/studio/gpu.Dockerfile
We would like to use GPU for training in AWS SageMaker Studio. This Dockerfile facilitates that experience. I've tested it with [this notebook](https://github.com/awslabs/djl/blob/master/jupyter/rank_classification_using_BERT_on_Amazon_Review.ipynb). 
=> Adding GPU dockerfile for SageMaker studio

android/quickdraw_recognition/build.gradle
=> bump android version to v0.10.0

.github/workflows/canary-centos.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, canary/build.gradle, canary/gradle.properties
=> Fix canary for the new version

README.md
=> add nightly test badge

apache-kafka/src/main/java/com/example/SentimentAnalysis.java
Apply code formatting on the code to pass the test
=> apply format

canary/build.gradle
Workround windows command line too long issue, reduce classpath length
=> [ci] Fix windows canary build failure

aws/emr-distributed-inference/dataprocess/build.gradle, djl-serving/README.md, djl-serving/java-mode/devEnv/build.gradle, djl-serving/python-mode/README.md
Update the demo version for DJLServing and Spark
=> update demo version

web-demo/interactive-console/src/main/java/ai/djl/examples/jshell/ShellController.java
=> fix format

.github/workflows/canary-centos.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, aws/beanstalk-model-serving/build.gradle, aws/emr-distributed-inference/dataprocess/build.gradle, canary/build.gradle, development/fatjar/build.gradle, development/fatjar/pom.xml, development/module/build.gradle, development/multi-engine/build.gradle, djl-serving/README.md, djl-serving/java-mode/devEnv/build.gradle, djl-serving/python-mode/README.md, footwear_classification/build.gradle, huggingface/hybrid/build.gradle, malicious-url-detector/build.gradle, web-demo/interactive-console/build.gradle, web-demo/interactive-console/src/main/resources/starter/mxnet.gradle, web-demo/interactive-console/src/main/resources/starter/pytorch.gradle, web-demo/interactive-console/src/main/resources/starter/tensorflow.gradle
=> Update to DJL 0.18.0

.github/workflows/canary-aarch64-linux.yml
Sample run https://github.com/deepjavalibrary/djl-demo/actions/runs/2828066660
Still working on gpu actions, I'll publish a separate PR for those once i resolve the issues.
=> Add aarch64 canary build

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-centos.yml, .github/workflows/canary-gpu-cuda-102.yml, .github/workflows/canary-gpu-cuda-112.yml, .github/workflows/canary-gpu-cuda-113.yml, .github/workflows/canary-gpu-cuda-116.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, canary/build.gradle, canary/src/main/java/ai/djl/canary/CanaryTest.java, gradle.properties
1. Upgrade pytorch to 1.12.1
2. Adds cuda116 canary test
3. Adds LightGBM canary test
4. Adds ONNXRuntime ARM canary test
5. Adds Huggingface tokenizer test
6. Adds XGBoost GPU test
7. Upgrade DJL to 0.19.0-SNAPSHOT
=> Upgrade pytorch to 1.12.1

aws/sagemaker/README.md, aws/sagemaker/large-model-inference/BYOC_template_with_LMI_solution.ipynb, aws/sagemaker/large-model-inference/README.md
Add template for future build application on LMI
=> add a few template in the DJL demo page

aws/sagemaker/large-model-inference/README.md, aws/sagemaker/large-model-inference/pysdk_template_with_LMI_solution.ipynb, aws/sagemaker/large-model-inference/standard_template_with_LMI_solution.ipynb
Add two more notebook to demo the use cases
=> add two more Notebooks

aws/sagemaker/large-model-inference/BYOC_template_with_LMI_solution.ipynb, aws/sagemaker/large-model-inference/pysdk_template_with_LMI_solution.ipynb, aws/sagemaker/large-model-inference/standard_template_with_LMI_solution.ipynb
=> bug fix in the code

aws/sagemaker/large-model-inference/standard_template_with_LMI_solution.ipynb
=> [template] update the content

aws/sagemaker/Multi-Model-Inference-Demo.ipynb
Add MME notebook with instructions
=> add MME demo notebook

apache-spark/spark3.0/audio-pyspark/README.md, apache-spark/spark3.0/audio-pyspark/speech_recognition.py, apache-spark/spark3.0/audio-pyspark/whisper_speech_recognition.py, aws/sagemaker/processing/djl_sagemaker_spark_processing_whisper_speech_recognition/code/process.py, aws/sagemaker/processing/djl_sagemaker_spark_processing_whisper_speech_recognition/djl_sagemaker_spark_processing_whisper_speech_recognition.ipynb
Add whisper python example
This example uses a light-weight short audio for demo purposes. I have tested that it will work if user passes a longer audio.
=> [spark] Add audio python example

footwear_classification/README.md, footwear_classification/build.gradle
Enabling support and providing documentation for running on M1 Macs
=> [M1 Macs] Enabling support and providing documentation for running on M1 Macs

aws/sagemaker/large-model-inference/.gitignore, aws/sagemaker/large-model-inference/README.md, aws/sagemaker/large-model-inference/sample-llm/deploy_llama2_70b.ipynb, aws/sagemaker/large-model-inference/sample-llm/llama_7b_customized_preprocessing.ipynb
Add customized logic for rolling batch
=> add customized model.py for rollingbatch

aws/sagemaker/large-model-inference/README.md, aws/sagemaker/large-model-inference/sample-llm/fastertransformer_deploy_pythia12b_triton_mode.ipynb
=> add fastertransformer demo

aws/sagemaker/large-model-inference/README.md, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_deploy_codellama_34b.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_llama_13b.ipynb
=> add vllm and code_llama model

aws/sagemaker/large-model-inference/README.md, aws/sagemaker/large-model-inference/sample-llm/tnx_rollingbatch_deploy_opt.ipynb
=> Add Transformer neuronx notebook samples

aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_llama_13b.ipynb
=> [vLLM demo] add pyarrow in the dependencies

aws/sagemaker/large-model-inference/README.md, aws/sagemaker/large-model-inference/sample-llm/tnx_rollingbatch_deploy_llama_13b.ipynb, aws/sagemaker/large-model-inference/sample-llm/tnx_rollingbatch_deploy_llama_7b_int8.ipynb
=> [INF2] add 2 LLAMA model for inference

aws/sagemaker/large-model-inference/README.md, aws/sagemaker/large-model-inference/sample-llm/hf_acc_deploy_mistral_7b.ipynb, aws/sagemaker/large-model-inference/sample-llm/hf_acc_rollingbatch_deploy_mistral_7b.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_mistral_7b.ipynb
Add Mistral 7b inference solution
=> add mistral 7b deployment guide

aws/sagemaker/large-model-inference/sample-llm/tnx_rollingbatch_deploy_llama_13b.ipynb, aws/sagemaker/large-model-inference/sample-llm/tnx_rollingbatch_deploy_llama_7b_int8.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_llama_13b.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_mistral_7b.ipynb
Update vLLM inference instruction
=> [vLLM][Notebook] update dependencies settings

aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_llama_13b.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_mistral_7b.ipynb
use different vLLM for different demos
=> [Notebook] fix different version for vllm

aws/sagemaker/README.md, aws/sagemaker/llm-instance-recommend/.gitignore, aws/sagemaker/llm-instance-recommend/README.md, aws/sagemaker/llm-instance-recommend/lmi_recommender/instance_recommender.py, aws/sagemaker/llm-instance-recommend/lmi_recommender/ir_strategy_maker.py, aws/sagemaker/llm-instance-recommend/lmi_recommender/lmi_config_recommender.py, aws/sagemaker/llm-instance-recommend/setup.py
Add inference recommendation toolkit for LMI containers
=> add inference recommendation toolkit for lmi

aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_llama_13b.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_mistral_7b.ipynb, aws/sagemaker/llm-instance-recommend/lmi_recommender/instance_recommender.py, aws/sagemaker/llm-instance-recommend/lmi_recommender/lmi_config_recommender.py
update mistral settings to use fixed HF versions
=> update mistral settings

aws/sagemaker/large-model-inference/README.md
This fixes the name so it shows on docs and adds a missing notebook to the index.
=> Updates lmi sample index

aws/sagemaker/large-model-inference/sample-llm/ds_deploy_llama2-13b-smoothquant.ipynb
Fix the error output from the deepspeed smoothquant notebook.
=> [fix] clear output for deepspeed demo

aws/sagemaker/large-model-inference/README.md
Adds the examples to our LLM notebook index.
=> Adds examples from AmazonSageMaker Examples

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-centos.yml, .github/workflows/canary-gpu.yml, .github/workflows/canary-m1-mac.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, .github/workflows/canary.yml
This uses the actions reusable workflows to add a single canary workflow that will run all of the other canary workflows
=> Creates Multi-canary

aws/sagemaker/large-model-inference/sample-llm/multi_lora_adapter_inference.ipynb
Follows https://github.com/deepjavalibrary/djl-serving/pull/1263
@rohithkrn
=> Update lora notebook with working model id

aws/sagemaker/llm-instance-recommend/lmi_recommender/lmi_config_recommender.py
Add SmoothQuant recommendation prioritized for INT8 precision
=> add smoothquant to recommender

aws/sagemaker/large-model-inference/README.md, aws/sagemaker/large-model-inference/sample-llm/ds_rollingbatch_deploy_llama2-13b-smoothquant.ipynb
https://github.com/deepjavalibrary/djl-demo/blob/ds_rolling_batch/aws/sagemaker/large-model-inference/sample-llm/ds_rollingbatch_deploy_llama2-13b-smoothquant.ipynb
=> [WIP] Adding notebook for DeepSpeed rolling batch

aws/sagemaker/large-model-inference/sample-llm/tnx_rollingbatch_deploy_llama_13b.ipynb, aws/sagemaker/large-model-inference/sample-llm/tnx_rollingbatch_deploy_llama_7b_int8.ipynb, aws/sagemaker/large-model-inference/sample-llm/tnx_rollingbatch_deploy_opt.ipynb
Updating versions and needed configuration for tnx notebooks
=> [docs] Updating tnx notebook versions for 0.25.0

aws/sagemaker/large-model-inference/sample-llm/trtllm_rollingbatch_deploy_llama_13b.ipynb
=> [docs] Fixes typo in TensorRT-LLM rolling batch jupyter notebook

aws/sagemaker/large-model-inference/sample-llm/lookahead_decoding_llama_7b.ipynb
https://lmsys.org/blog/2023-11-21-lookahead-decoding/
in my tests drop from 38 sec to 28 sec for 1024 tokens, with no decrease in accuracy.
=> Add lookeahead decoding sample for llama-2

aws/sagemaker/large-model-inference/README.md, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_llama_7b_stop_reason.ipynb
Add a sample with stop reasons
=> allow stop reason with rolling batch

apache-spark/notebook/Image_Classification_Spark.ipynb, apache-spark/notebook/Text_Embedding_Spark.ipynb, apache-spark/notebook/Text_Encoding_Spark.ipynb, apache-spark/notebook/Text_Tokenization_Spark.ipynb, apache-spark/spark3.0/audio/README.md, apache-spark/spark3.0/audio/build.sbt, apache-spark/spark3.0/image/README.md, apache-spark/spark3.0/image/build.sbt, apache-spark/spark3.0/text/README.md, apache-spark/spark3.0/text/build.gradle, apache-spark/spark3.0/text/build.sbt, aws/sagemaker/large-model-inference/sample-llm/fastertransformer_deploy_pythia12b_triton_mode.ipynb, aws/sagemaker/large-model-inference/sample-llm/hf_acc_deploy_llama_7b_customized_preprocessing.ipynb, aws/sagemaker/large-model-inference/sample-llm/hf_acc_deploy_mistral_7b.ipynb, aws/sagemaker/large-model-inference/sample-llm/lookahead_decoding_llama_7b.ipynb, aws/sagemaker/large-model-inference/sample-llm/multi_lora_adapter_inference.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_llama_7b_customized_preprocessing.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_llama_13b.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_mistral_7b.ipynb, aws/sagemaker/large-model-inference/standard_template_with_LMI_solution.ipynb, aws/sagemaker/processing/djl_sagemaker_spark_processing_binary/djl_sagemaker_spark_processing_binary.ipynb, aws/sagemaker/processing/djl_sagemaker_spark_processing_image_classification/djl_sagemaker_spark_processing_image_classification.ipynb, aws/sagemaker/processing/djl_sagemaker_spark_processing_text2text_generation/djl_sagemaker_spark_processing_text2text_generation.ipynb, aws/sagemaker/processing/djl_sagemaker_spark_processing_text_classification/djl_sagemaker_spark_processing_text_classification.ipynb, aws/sagemaker/processing/djl_sagemaker_spark_processing_text_generation/djl_sagemaker_spark_processing_text_generation.ipynb, aws/sagemaker/processing/djl_sagemaker_spark_processing_whisper_speech_recognition/djl_sagemaker_spark_processing_whisper_speech_recognition.ipynb, djl-serving/java-client/gradle.properties
updates the demo notebooks and spark examples for djl 0.25.0
=> [jupyter][spark] update notebooks and spark demos to djl 0.25.0

aws/sagemaker/large-model-inference/README.md, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_llama_7b_chat.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_llama_7b_customized_preprocessing.ipynb
=> add LLAMA 7B chat model

malicious-url-detector/docs/dataset_creation.md
=> [docs] Fixed dataset creation markdown format

aws/sagemaker/large-model-inference/sample-llm/ds_deploy_llama2-13b-smoothquant.ipynb, aws/sagemaker/large-model-inference/sample-llm/ds_rollingbatch_deploy_gpt-neox-20b-smoothquant.ipynb, aws/sagemaker/large-model-inference/sample-llm/ds_rollingbatch_deploy_llama2-13b-smoothquant.ipynb, aws/sagemaker/large-model-inference/sample-llm/hf_acc_deploy_codellama_34b.ipynb, aws/sagemaker/large-model-inference/sample-llm/hf_acc_deploy_falcon_40b.ipynb, aws/sagemaker/large-model-inference/sample-llm/hf_acc_deploy_llama2_13b_gptq.ipynb, aws/sagemaker/large-model-inference/sample-llm/hf_acc_deploy_llama2_70b-2.ipynb, aws/sagemaker/large-model-inference/sample-llm/hf_acc_deploy_llama2_70b.ipynb, aws/sagemaker/large-model-inference/sample-llm/hf_acc_deploy_llama_7b_customized_preprocessing.ipynb, aws/sagemaker/large-model-inference/sample-llm/hf_acc_deploy_mistral_7b.ipynb, aws/sagemaker/large-model-inference/sample-llm/lookahead_decoding_llama_7b.ipynb, aws/sagemaker/large-model-inference/sample-llm/multi_lora_adapter_inference.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_deploy_codegen25_7b.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_deploy_codellama_34b.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_deploy_falcon_40b.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_deploy_flan_ul2.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_deploy_llama2-13b-gptq.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_deploy_llama2-70b-gptq.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_deploy_llama2_70b.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_deploy_mpt_30b.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_deploy_octocoder_w_pagedattn.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_llama_7b_chat.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_llama_7b_customized_preprocessing.ipynb, aws/sagemaker/large-model-inference/sample-llm/rollingbatch_llama_7b_stop_reason.ipynb, aws/sagemaker/large-model-inference/sample-llm/tnx_rollingbatch_deploy_llama_7b_int8.ipynb, aws/sagemaker/large-model-inference/sample-llm/tnx_rollingbatch_deploy_opt.ipynb, aws/sagemaker/large-model-inference/sample-llm/trtllm_rollingbatch_deploy_llama_13b.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_llama_13b.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_mistral_7b.ipynb
=> Update notebooks to djl 0.26.0

.github/workflows/canary-model-zoo.yml, .github/workflows/canary.yml, .github/workflows/nightly.yml, .github/workflows/publish-job-success.yml
publish cloudwatch metrics for scheduled workflow runs
=> [ci] add cloudwatch metrics for scheduled workflow failures

.github/workflows/publish-job-success.yml
fix typo in publish metric workflow
=> [fix][ci] fix typo in publish metric workflow

android/gradle.properties, android/onnxruntime_android/build.gradle, android/onnxruntime_android/object_detection/build.gradle, android/pytorch_android/face_detection/build.gradle, android/pytorch_android/neural_machine_translation/build.gradle, android/pytorch_android/quickdraw_recognition/build.gradle, android/pytorch_android/semantic_segmentation/build.gradle, android/pytorch_android/speech_recognition/build.gradle, android/pytorch_android/style_transfer_cyclegan/build.gradle
=> [android] Upgrade to 0.26.0 and workaround common-compress issue

aws/sagemaker/large-model-inference/sample-llm/trtllm_rollingbatch_deploy_customized_processing.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_rollingbatch_deploy_customized_processing.ipynb
Fixing an incorrect type in one of the comments in the notebook
=> correct comment

development/fatjar/README.md
=> [docs] Updates offline mode document

aws/sagemaker/large-model-inference/sample-llm/aws-under-the-hood-neuron-demo.ipynb
Adding a demo notebook for neuron chat model.
=> [sagemaker] add aws neuron demo for sagemaker

aws/sagemaker/large-model-inference/sample-llm/aws-under-the-hood-neuron-demo.ipynb
Add specific model, and update the compile times for the model since demo was done using compiled model but this notebook does runtime compilation.
=> [sagemaker] update aws neuron demo for sagemaker

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-centos.yml, .github/workflows/canary-gpu.yml, .github/workflows/canary-m1-mac.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml
=> Remove pytorch 2.0.1 from canary

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-centos.yml, .github/workflows/canary-gpu.yml, .github/workflows/canary-m1-mac.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-model-zoo.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, .github/workflows/nightly.yml
=> [ci] Updates to use JDK 17

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-centos.yml, .github/workflows/canary-gpu.yml, .github/workflows/canary-m1-mac.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, canary/build.gradle, canary/src/main/java/ai/djl/canary/CanaryTest.java
=> [canary] Updates pytorch to 2.1.2

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-centos.yml, .github/workflows/canary-gpu.yml, .github/workflows/canary-m1-mac.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, canary/build.gradle
=> [canary] Updates PyTorch to 2.2.2

gradle/wrapper/gradle-wrapper.properties
=> [ci] Upgrades gradle to 8.5

aws/sagemaker/large-model-inference/sample-llm/trtllm_dynamicbatch_flant5-xl.ipynb
=> google/flan-t5-xl notebbok for TensorRT-LLM

development/module/build.gradle, development/module/src/main/java/module-info.java, development/module/src/main/java/org/examples/module/ModuleTest.java, gradle.properties
=> Upgrade DJL version to 0.28.0

live-object-detection/build.gradle, live-object-detection/src/main/java/com/examples/WebCam.java
=> [live-web-cam] Use PyTorch yolo model

footwear_classification/README.md, footwear_classification/build.gradle, footwear_classification/src/main/java/com/examples/Inference.java
=> [footware] download model for inference

aws/lambda-model-serving/README.md, aws/lambda-model-serving/build.gradle, aws/lambda-model-serving/src/main/java/com/examples/Handler.java, aws/lambda-model-serving/src/main/java/com/examples/Request.java, aws/lambda-model-serving/src/test/java/com/examples/HandlerTest.java
=> [lambda] Replace MXNet model with PyTorch for lambda demo

aws/aws-kinesis-video-streams/build.gradle, aws/aws-kinesis-video-streams/src/main/java/com/examples/DjlImageVisitor.java
=> Use PyTorch yolo model for kinesis demo

apache-flink/sentence_embedding/build.gradle, apache-flink/sentence_embedding/src/main/java/com/example/SentenceEncoder.java, apache-flink/sentiment-analysis/build.gradle, apache-flink/sentiment-analysis/src/main/java/com/example/SentimentAnalysis.java, development/python/src/main/java/com/examples/PythonTranslator.java, djl-serving/wlm/flink-sentiment-analysis/build.gradle, djl-serving/wlm/flink-sentiment-analysis/src/main/java/com/example/SentimentAnalysis.java
=> [flink] Fixes flink demos

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-centos.yml, .github/workflows/canary-gpu.yml, .github/workflows/canary-m1-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml
=> [canary] Adds PyTorch 2.3.0 to canary test

development/multi-engine/src/main/java/com/examples/MultiEngine.java, development/python/build.gradle.kts, djl-serving/wlm/flink-sentiment-analysis/build.gradle.kts, djl-serving/workflows/java-pre-post-processing/function/build.gradle.kts, djl-serving/workflows/multi-model/function/build.gradle.kts, huggingface/hybrid/build.gradle.kts, malicious-url-detector/src/main/java/com/example/CSVDataset.java, tools/gradle/javaFormatter.gradle.kts
=> [ci] Fixes 0.28.0 SNAPSHOT version issue

aws/sagemaker/large-model-inference/sample-llm/text_embedding_deploy_bert.ipynb
=> Add text embedding example notebook

pneumonia-detection/src/main/java/com/examples/PneumoniaDetection.java
=> [PneumoniaDetection] log failure for macOS M1

aws/sagemaker/large-model-inference/sample-llm/text_embedding_deploy_bert.ipynb
=> [lmi] Updates text embedding jupyter notebook

aws/sagemaker/processing/djl_sagemaker_spark_processing_text_classification/djl_sagemaker_spark_processing_text_classification.ipynb
=> [spark] Fix input_col in spark example notebooks

aws/sagemaker/large-model-inference/sample-llm/text_embedding_deploy_bert.ipynb
=> [jupyter] Updates text embedding example jupyter notebook

quarkus/extension/deployment/pom.xml, quarkus/extension/runtime/pom.xml
=> [quarkus] Bumps up DJL version to 0.28.0

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-centos.yml, .github/workflows/canary-gpu.yml, .github/workflows/canary-m1-mac.yml, .github/workflows/canary-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, canary/build.gradle.kts
=> [canary] Test DJL 0.29.0-SNAPSHOT version

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-centos.yml, .github/workflows/canary-gpu.yml, .github/workflows/canary-m1-mac.yml, canary/build.gradle.kts
=> [canary] Updates tensorflow to 1.16.1

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-centos.yml
=> [canary] Fixes nodejs 20 issues

jupyter/transfer_learning_on_cifar10.ipynb
=> [jupyter] Updates transfer learning jupyter to use PyTorch

aws/sagemaker/large-model-inference/sample-llm/tnx_speculative_decoding_deploy_llama2_70b.ipynb
Adding an example deployment of the batch size 1 speculative decoding for LMI Neuron
=> [docs] lmi neuron speculative decoding notebook

aws/sagemaker/large-model-inference/README.md
=> [jupyter] Update llm samples README file

canary/build.gradle.kts, djl-serving/wlm/flink-sentiment-analysis/build.gradle.kts, gradle.properties
=> Updates to DJL 0.29.0 release build

jupyter/transfer_learning_on_cifar10.ipynb, quarkus/extension-example/pom.xml, quarkus/extension/deployment/pom.xml, quarkus/extension/runtime/pom.xml, visualization-vue/djl-training-demo/pom.xml
=> Up version to 0.29.0

jupyter/BERTQA.ipynb, jupyter/load_mxnet_model.ipynb, jupyter/load_pytorch_model.ipynb, jupyter/mxnet/load_your_own_mxnet_bert.ipynb, jupyter/object_detection_with_model_zoo.ipynb, jupyter/onnxruntime/machine_learning_with_ONNXRuntime.ipynb, jupyter/pytorch/load_your_own_pytorch_bert.ipynb, jupyter/rank_classification_using_BERT_on_Amazon_Review.ipynb, jupyter/tensorflow/pneumonia_detection.ipynb, jupyter/tensorflow/rank_classification_using_BERT_on_Amazon_Review.ipynb, jupyter/tutorial/01_create_your_first_network.ipynb, jupyter/tutorial/02_train_your_first_model.ipynb, jupyter/tutorial/03_image_classification_with_your_model.ipynb
=> [jupyter] Updates jupyter notebooks to 0.28.0

huggingface/nlp/src/main/java/com/examples/Reranking.java
=> [nlp] Adds Reranking model demo

aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_llama_13b.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_mistral_7b.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_rollingbatch_deploy_Mixtral-8x7B-DPO-AWQ.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_rollingbatch_deploy_mixtral_8x7b.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_rollingbatch_deploy_mixtral_8x7b_quantized_AWQ.ipynb, aws/sagemaker/large-model-inference/sample-llm/vllm_rollingbatch_deploy_yi_34B_chat_4bits_AWQ.ipynb
=> [llm] Updates jupyter notebooks for 0.28.0 DLC release

aws/sagemaker/large-model-inference/sample-llm/hf_acc_deploy_codellama_34b.ipynb, aws/sagemaker/large-model-inference/sample-llm/hf_acc_deploy_llama2_13b_gptq.ipynb, aws/sagemaker/large-model-inference/sample-llm/hf_acc_deploy_mistral_7b.ipynb
=> [llm] Updates jupyter notebooks for 0.28.0 DLC release - part2

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-al2.yml, .github/workflows/canary-gpu.yml, .github/workflows/canary-m1-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, canary/build.gradle.kts
=> [canary] Updates PyTorch to 2.4.0-SNAPSHOT

.github/workflows/canary-gpu.yml, canary/build.gradle.kts
=> [canary] Fixes canary build for PyTorch to 2.4.0

canary/build.gradle.kts
bumps canary to 0.30 so that it runs on the development version
=> bump canary to 0.30

aws/sagemaker/large-model-inference/sample-llm/multi-modal-llava-v1-6.ipynb
Adding a multimodal example notebook for lmi v11
=> [notebook][sagemaker] add multimodal example notebook

README.md, development/python/README.md, djl-serving/multi-node/README.md, djl-serving/workflows/java-pre-post-processing/README.md, djl-serving/workflows/multi-model/README.md, djl-serving/workflows/python-pre-post-processing/README.md, djl-serving/workflows/python/README.md
=> [docs] Fixing relative path

visualization-vue/djl-training-ui/package.json
=> [vue] Updates axios to 1.7.3

aws/sagemaker/large-model-inference/sample-llm/reranking_bge_reranker_v2_m3.ipynb
=> [jupyter] Add reranker model example

aws/sagemaker/large-model-inference/sample-llm/zero_shot_image_classification_grounding-dino-base.ipynb
=> [jupyter] Adds zero_shot_image_classification example jupyter notebook

development/python/build.gradle.kts
=> Use to DJL release build for python demo

malicious-url-detector/docs/training_model.md, malicious-url-detector/docs/translators.md
=> [docs] fix typos

apache-beam/ctr-prediction/README.md, apache-spark/image-classification/README.md, aws/beanstalk-model-serving/README.md
Hello
While looking through your docs I found and fixed several spelling issues.
=> Docs fix spelling issues

canary/src/main/java/ai/djl/canary/CanaryTest.java
=> [canary] Fixes canary test

gradle.properties
=> Updates dependencies version

djl-serving/multi-node/lws.yaml
=> Update DJL Serving multi-node example lws.yaml

android/gradle.properties, apache-beam/ctr-prediction/pom.xml, apache-spark/image-classification/build.sbt, apache-spark/spark3.0/audio/README.md, apache-spark/spark3.0/audio/build.sbt, apache-spark/spark3.0/image/README.md, apache-spark/spark3.0/image/build.sbt, apache-spark/spark3.0/text/README.md, apache-spark/spark3.0/text/build.sbt, development/fatjar/build.sbt, development/fatjar/pom.xml, djl-serving/README.md, djl-serving/python-mode/stable-diffusion/docs/README.md, graalvm/pom.xml, huggingface/inferentia/README.md, huggingface/inferentia/deploy_on_sagemaker.md, quarkus/example/pom.xml, quarkus/extension-example/pom.xml, quarkus/extension/deployment/pom.xml, quarkus/extension/runtime/pom.xml, visualization-vue/djl-training-demo/pom.xml
=> Update to DJL 0.30.0

apache-flink/image-classification/src/main/java/com/example/EMI.java, gradle/wrapper/gradle-wrapper.properties, huggingface/nlp/build.gradle.kts
=> [ci] Updates gradle to 8.10.1

gradle/wrapper/gradle-wrapper.properties
=> [gradle] Fixes gradle wrapper url

aws/sagemaker/large-model-inference/sample-llm/multi_lora_adapter_inference.ipynb
=> Update multi adapter lora notebook

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-al2.yml, .github/workflows/canary-gpu.yml, .github/workflows/canary-m1-mac.yml, .github/workflows/canary-ubuntu.yml, .github/workflows/canary-windows.yml, canary/build.gradle.kts, gradle.properties
=> [canary] Adds PyTorch 2.5.1 to canary test

aws/sagemaker/large-model-inference/README.md, aws/sagemaker/large-model-inference/sample-llm/multi_lora_adapter_inference.ipynb, aws/sagemaker/large-model-inference/sample-llm/multi_lora_adapter_inference_custom.ipynb
=> [lmi] Rename advanced lora notebook to custom lora notebook

aws/sagemaker/large-model-inference/sample-llm/lmi-async-inference-demo.ipynb
Adding a demo for async inference. This has been a request from many customers, and with the 0.31.0 release it is now possible.
=> Adding sagemaker async inference demo

aws/sagemaker/large-model-inference/sample-llm/reranking_bge_reranker_v2_m3.ipynb, aws/sagemaker/large-model-inference/sample-llm/text_embedding_deploy_bert.ipynb
=> Update text embedding notebooks

canary/build.gradle.kts
=> [canary] update djl version to latest snapshot

graalvm/README.md, malicious-url-detector/src/main/java/com/example/FilterProxy.java
=> chore: fix some typos in comment

gradle/wrapper/gradle-wrapper.properties
=> [ci] Upgrade gradle to 8.12

footwear_classification/src/main/java/com/examples/Inference.java, footwear_classification/src/main/java/com/examples/Training.java, malicious-url-detector/src/main/java/com/example/FilterProxy.java
#541
force 100x100 crop for inference
=> fix img target size mismatch issue during inference

canary/build.gradle.kts, canary/src/main/java/ai/djl/canary/ModelZooTest.java, gradle.properties, gradle/wrapper/gradle-wrapper.properties
=> Updates DJL version to 0.33.0-SNAPSHOT

jupyter/Dockerfile
upgrade to ubuntu:24.04 with JDK 17 in Dockerfile ( Jupyter Example )
https://github.com/deepjavalibrary/djl-demo/pull/551#issuecomment-2802873500
=> upgrade to ubuntu:24.04 with JDK 17 (jupyter Dockerfile )

android/.gitignore, android/gradle.properties, canary/build.gradle.kts, djl-serving/wlm/flink-sentiment-analysis/build.gradle.kts, djl-serving/workflows/java-pre-post-processing/function/build.gradle.kts, djl-serving/workflows/multi-model/function/build.gradle.kts, gradle.properties, huggingface/hybrid/build.gradle.kts
=> Updates DJL version

jupyter/BERTQA.ipynb, jupyter/load_mxnet_model.ipynb, jupyter/load_pytorch_model.ipynb, jupyter/mxnet/load_your_own_mxnet_bert.ipynb, jupyter/object_detection_with_model_zoo.ipynb, jupyter/onnxruntime/machine_learning_with_ONNXRuntime.ipynb, jupyter/pytorch/load_your_own_pytorch_bert.ipynb, jupyter/rank_classification_using_BERT_on_Amazon_Review.ipynb, jupyter/tensorflow/pneumonia_detection.ipynb, jupyter/tensorflow/rank_classification_using_BERT_on_Amazon_Review.ipynb, jupyter/transfer_learning_on_cifar10.ipynb, jupyter/tutorial/01_create_your_first_network.ipynb, jupyter/tutorial/02_train_your_first_model.ipynb, jupyter/tutorial/03_image_classification_with_your_model.ipynb
=> Update sonatype snapshot url for jupyter notebook

canary/build.gradle.kts
=> [canary] Use PyTorch 2.7.1 SNAPSHOT version

.github/workflows/canary-aarch64-linux.yml, .github/workflows/canary-al2.yml, .github/workflows/canary-gpu.yml, canary/build.gradle.kts, canary/src/main/java/ai/djl/canary/CanaryTest.java, gradle.properties
=> [fix] Fix canary CI build

.github/workflows/canary-gpu.yml
=> Fix canary github action

aws/emr-distributed-inference/image-classification-gpu/build.gradle.kts, gradle.properties, gradle/wrapper/gradle-wrapper.properties, tools/gradle/javaFormatter.gradle.kts, web-demo/interactive-console/build.gradle.kts
=> Update gradle to 9.0.0

aws/sagemaker/large-model-inference/sample-llm/stateful_inference_llama3_8b.ipynb
=> Update stateful inference notebook packages

aws/sagemaker/large-model-inference/sample-llm/stateful_inference_llama3_8b.ipynb
=> Use UTC timezone for session expiration ts
